// <auto-generated />
using System;
using BlazeGate.Model.Sample.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazeGate.Model.Sample.EFCore.Migrations
{
    [DbContext(typeof(BlazeGateSampleContext))]
    partial class BlazeGateSampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazeGate.Model.Sample.EFCore.TB_Dictionary", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("dateTime")
                        .HasComment("创建时间");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasComment("是否启用");

                    b.Property<string>("Extended")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("扩展");

                    b.Property<string>("Extended2")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("扩展2");

                    b.Property<string>("Extended3")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("扩展3");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("键");

                    b.Property<int>("NumberIndex")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("类型");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("dateTime")
                        .HasComment("更新时间");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("值");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "Key")
                        .IsUnique();

                    b.ToTable("TB_Dictionary", t =>
                        {
                            t.HasComment("字典表");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
